[project]
name = "das-pipeline"
version = "0.1.0"
dependencies = [
    "typer>=0.27",
    "pydantic>=2.13",
    "dascore>=0.1.20",
    "obspy>=1.5",
    "pyyaml>=6.0",
    "matplotlib>=3.11",
    "scipy>=1.18",
    "numpy>=2.5",
    "pandas>=3.0",
    "typing_extensions>=4.16",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[project.scripts]
das-pipeline = "das_pipeline.cli:app"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"